#!/bin/bash

# install bower to manage the frontend dependencies
sudo bower install --allow-root

# to compile the css
gem install sass
# to import the sass variables from a json file
gem install sass-json-vars
# to install the frontend dependencies
npm i -g bower
subo npm i -g grunticon-cli

# set up the project credentials for the deployment
brew install ssh-copy-id