#!/bin/bash

# install bower to manage the frontend dependencies
@ bower install
# to compile the css
@ gem install sass
# to import the sass variables from a json file
@ gem install sass-json-vars
# to install the frontend dependencies
@ npm install -g bower