global-variables:
  image_sm_php: &image_sm_php goldinteractive/sm-php:7.3-rev2
  image_sm_node: &image_sm_node goldinteractive/sm-node:10.17-rev2

kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./backend/vendor
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install-fe
    image: *image_sm_node
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/frontend/install.sh
    depends_on:
      - restore-cache

  - name: icons-optimize
    image:  *image_sm_node
    commands:
      - .scripts/ci/icons-optimize.sh
    depends_on:
      - install-fe

  - name: icons-compile
    image: *image_sm_php
    commands:
      - .scripts/ci/icons-compile.sh
    depends_on:
      - icons-optimize

  - name: favicons
    image: v4tech/imagemagick:latest
    commands:
      - .scripts/ci/favicons.sh
    depends_on:
      - icons-compile

  - name: build-fe
    image: *image_sm_node
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/ci/build-fe.sh
    depends_on:
      - favicons

  - name: build-designsystem
    image: *image_sm_node
    environment:
        ASSET_HASH: ${DRONE_BUILD_CREATED}
        ENV: ${DRONE_BRANCH##release/}
    commands:
        - .scripts/ci/build-designsystem.sh
    depends_on:
        - build-fe

  - name: test-fe
    image: *image_sm_node
    commands:
      - .scripts/ci/test-fe.sh
    depends_on:
      - build-fe

  - name: install-be
    image: *image_sm_php
    commands:
      - .scripts/backend/install.sh
    depends_on:
      - restore-cache

  - name: build-be
    image: *image_sm_php
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/ci/build-be.sh
      - .scripts/ci/post-build.sh
    depends_on:
      - install-be

  - name: test-be
    image: *image_sm_php
    commands:
      - .scripts/ci/test-be.sh
    depends_on:
      - build-be

  - name: deploy
    image: appleboy/drone-scp
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/deploy.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password
    depends_on:
      - test-fe
      - test-be
      - build-designsystem

  - name: golive
    image: appleboy/drone-ssh
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/golive.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password
      DB_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_db_password
    depends_on:
      - deploy

#  - name: notify
#    image: goldinteractive/drone-google-chat
#    settings:
#        webhook: "REPLACEME"
#        key: 'REPLACEME'
#        token: 'REPLACEME'
#        template: >
#            {{#success build.status}}
#              *Success*: *{{repo.name}}* (#{{build.number}}) by *{{build.author.name}}* deployed (*{{build.branch}}*). Yay.
#            {{else}}
#              *Failure*: *{{repo.name}}* (#{{build.number}}) by *{{build.author.name}}* was not deployed (*{{build.branch}}*). Oh noes.
#            {{/success}}
#    depends_on:
#      - golive
#    when:
#      status: [ success, failure ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./backend/vendor
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - golive

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - release/staging
    - release/production
