global-variables:
  image_sm_php: &image_sm_php goldinteractive/sm-php:7.3-rev2
  image_sm_node: &image_sm_node goldinteractive/sm-node:10.17-rev2

kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./backend/vendor
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

  - name: install-fe
    image: *image_sm_node
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/frontend/install.sh

  - name: icons-optimize
    image:  *image_sm_node
    commands:
      - .scripts/ci/icons-optimize.sh

  - name: icons-compile
    image: *image_sm_php
    commands:
      - .scripts/ci/icons-compile.sh

  - name: favicons
    image: v4tech/imagemagick:latest
    commands:
      - .scripts/ci/favicons.sh

  - name: build-fe
    image: *image_sm_node
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/ci/build-fe.sh

  - name: test-fe
    image: *image_sm_node
    commands:
      - .scripts/ci/test-fe.sh

  - name: install-be
    image: *image_sm_php
    commands:
      - .scripts/backend/install.sh

  - name: build-be
    image: *image_sm_php
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/ci/build-be.sh
      - .scripts/ci/post-build.sh

  - name: test-be
    image: *image_sm_php
    commands:
      - .scripts/ci/test-be.sh

  - name: deploy
    image: appleboy/drone-scp
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/deploy.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password

  - name: golive
    image: appleboy/drone-ssh
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/golive.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password
      DB_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_db_password

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook: "REPLACEME"
#      template: >
#        {{#success build.status}}
#          *{{repo.name}}* (#{{build.number}}) by *{{build.author.name}}* deployed (*{{build.branch}}*). Yay.
#        {{else}}
#          *{{repo.name}}* (#{{build.number}}) by *{{build.author.name}}* was not deployed (*{{build.branch}}*). Oh noes.
#        {{/success}}
#    when:
#      status: [ success, failure ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./backend/vendor
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - release/staging
    - release/production