kind: pipeline
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./backend/vendor
        - ./frontend/node_modules
    volumes:
      - name: cache
        path: /cache

  - name: build
    image: goldinteractive/sackmesser:3.1
    environment:
      ASSET_HASH: ${DRONE_BUILD_CREATED}
      ENV: ${DRONE_BRANCH##release/}
    commands:
      - .scripts/ci/build-be.sh
      - .scripts/ci/build-fe.sh
      - .scripts/ci/post-build.sh

  - name: test
    image: goldinteractive/sackmesser:3.1
    commands:
      - .scripts/ci/test-be.sh
      - .scripts/ci/test-fe.sh

  - name: deploy
    image: appleboy/drone-scp
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/deploy.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password

  - name: golive
    image: appleboy/drone-ssh
    commands:
      - ENV=${DRONE_BRANCH##release/} .scripts/ci/golive.sh
    environment:
      SSH_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_password
      DB_PASSWORD:
        from_secret: deploy_${DRONE_BRANCH##release/}_db_password

#  - name: slack
#    image: plugins/slack
#    settings:
#      webhook: "REPLACEME"
#      template: >
#        {{#success build.status}}
#          *{{repo.name}}* (#{{build.number}}) by *{{build.author}}* deployed (*{{build.branch}}*). Yay.
#        {{else}}
#          *{{repo.name}}* (#{{build.number}}) by *{{build.author}}* was not deployed (*{{build.branch}}*). Oh noes.
#        {{/success}}
#    when:
#      status: [ success, failure ]

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./backend/vendor
        - ./node_modules
    volumes:
      - name: cache
        path: /cache

volumes:
  - name: cache
    host:
      path: /tmp/cache

trigger:
  branch:
    - release/staging
    - release/production