#  Documentation
#  https://github.com/causes/scss-lint/blob/master/lib/scss_lint/linter/README.md
#  https://github.com/causes/scss-lint/blob/master/config/default.yml
linters:
  BorderZero:
    enabled: false

  Indentation:
    enabled: true
    width: 2

  Compass::*:
    enabled: true

  Comment:
    enabled: false

  NameFormat:
    enabled: false

  PropertySortOrder:
    enabled: false

  SpaceAfterPropertyColon:
    enabled: true
    style: no_space # or 'no_space', or 'at_least_one_space', or 'aligned'

  SpaceAfterPropertyName:
    enabled: true

  SpaceBeforeBrace:
    enabled: true
    allow_single_line_padding: false

  SpaceBetweenParens:
    enabled: true
    spaces: 0

  SelectorDepth:
      enabled: true
      max_depth: 4