version: '3.7'

volumes:
  v_node_modules:
  v_node_modules_empty:
  v_vendor:

services:
  apache:
    image: goldinteractive/sm-apache:2.4-rev1
    ports:
      - ${DOCKER_PORT_WEB:-8000}:80
    volumes:
      - ./public:/var/www/public:delegated
      - ./_data:/var/www/_data:delegated
    networks:
      app-network:
        aliases:
          - apache
    depends_on:
      - backend
      - frontend

  frontend:
    image: goldinteractive/sm-node:12.13-rev1
    entrypoint: "tail -f /dev/null"
    volumes:
      - ./:/usr/src/app/:delegated
      - v_node_modules:/usr/src/app/node_modules
    networks:
      app-network:
        aliases:
          - frontend

  backend:
    image: goldinteractive/sm-php:7.3-rev2
    volumes:
      - ./:/var/www/:delegated
      - v_vendor:/var/www/backend/vendor
      - v_node_modules_empty:/var/www/node_modules
      - ~/.composer/auth.json:/root/.composer/auth.json
    networks:
      app-network:
        aliases:
          - backend

  designsystem:
      image: goldinteractive/sm-node:12.13-rev1
      ports:
          - 3002:3002
      entrypoint: "tail -f /dev/null"
      volumes:
          - ./:/usr/src/app/:delegated
          - v_node_modules:/usr/src/app/node_modules
      networks:
          app-network:
              aliases:
                  - designsystem
networks:
  app-network:
    driver: bridge
