version: '3.1'

volumes:
  v_node_modules:
  v_vendor:
  v_dist:
services:
  app:
    build:
      context: ./
      dockerfile: dockerfile.app
    working_dir: /var/www
    volumes:
      - ./:/var/www/:cached
      - v_node_modules:/var/www/node_modules
      - v_vendor:/var/www/backend/vendor
      - v_dist:/var/www/dist
      - ~/.composer/auth.json:/root/.composer/auth.json

  web:
    build:
      context: ./
      dockerfile: dockerfile.web
    working_dir: /var/www
    volumes:
      - ./_data:/var/www/_data:cached
      - ./public:/var/www/public:cached
    ports:
      - ${DOCKER_PORT_WEB:-8000}:80