#!/bin/bash


# install the frontend dependencies
if [ -f .bowerrc ]; then
  bower install
fi

# install the nodejs dependencies
if [ -f package.json ]; then
  sudo npm install
fi

# install the php dependencies (because we all love php!!!)
if [ -f composer.json ]; then
  sudo composer install --prefer-dist
fi