#!/bin/bash

# install and yarn to manage the frontend dependencies
brew update
brew install yarn
npm i -g bower

# to compile the css
gem install sass
# to import the sass variables from a json file
gem install sass-json-vars

# to install the frontend dependencies
sudo npm i -g grunticon-cli

# set up the project credentials for the deployment
brew install ssh-copy-id
