#!/bin/bash

echo 'Copying the root folders'
rsync -avtR --ignore-errors . $DEST \
      --exclude=$ASSETS_PATH \
      --exclude='/dist' \
      --exclude='/node_modules' \
      --exclude='Makefile' \
      --exclude='LICENSE' \
      --exclude='/*.*' \
      --exclude='.*' \
      --exclude='.*/' \
      --exclude='craft/storage/backups/*' \
      --exclude='craft/storage/runtime/*' \
      --exclude='/public/files'

# copy the important root files
echo 'Copying the root files'
rsync -dv --ignore-errors *.* $DEST \
      --exclude='*/' \
      --exclude='.*' \
      --exclude='*.md' \
      --exclude='*.js' \
      --exclude='*.json'

# copy the assets excluding the js, vendor and scss folder
echo 'Copying the assets files'
rsync -avtR --ignore-errors $ASSETS_PATH $DEST \
      --exclude='scss' \
      --exclude='img/icons' \
      --exclude='grid.*' \
      --exclude='*.scss.*' \
      --exclude='vendor' \
      --exclude='js' \
      --exclude='.*' \
      --exclude='.*/'

# move the js generated into the right folder
echo 'Copying the js file generated'
rsync -avR --ignore-errors $JS_BASE/$JS_OUT $DEST

