#!/bin/bash

# install the frontend dependencies
if [ -f .bowerrc ]; then
  bower install
fi

# install the npm dependencies
if [ -f package.json ]; then
  yarn install
fi

# install the php dependencies (because we all love php!!!)
if [ -f composer.json ]; then
  composer install --prefer-dist
fi

# first time css and javascript compilation
make css && make js
