#!/bin/bash

# install the frontend dependencies
if [ -f package.json ]; then
  yarn install
fi

# install the php dependencies (because we all love php!!!)
if [ -f composer.json ]; then
  composer install --prefer-dist
fi